08/07/2026

Assignment : 19

NumPy assignment : 2

In [1]:
# Question 1
import numpy as np

arr = np.arange(1, 21)

print("Array:", arr)
print("First element:", arr[0])

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First element: 1


In [2]:
# Question 2
print("Last element:", arr[-1])

Last element: 20


In [3]:
# Question 3
print("Third element:", arr[2])

Third element: 3


In [4]:
# Question 4
print("Last five elements:", arr[-5:])

Last five elements: [16 17 18 19 20]


In [5]:
# Question 5
print("Elements from index 3 to 8:", arr[3:9])

Elements from index 3 to 8: [4 5 6 7 8 9]


In [6]:
# Question 6
matrix = np.arange(1, 17).reshape(4, 4)

print("Matrix:")
print(matrix)

print("First row:", matrix[0])

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row: [1 2 3 4]


In [8]:
# Question 7
print("Last row:", matrix[-1])

Last row: [13 14 15 16]


In [9]:
# Question 8
print("First column:", matrix[:, 0])

First column: [ 1  5  9 13]


In [10]:
# Question 9
print("Last column:", matrix[:, -1])

Last column: [ 4  8 12 16]


In [11]:
# Question 10
print("Middle two rows:")
print(matrix[1:3])

Middle two rows:
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
# Question 11
print("Middle two columns:")
print(matrix[:, 1:3])

Middle two columns:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [13]:
# Question 12
print("First 2 × 2 sub-matrix:")
print(matrix[:2, :2])

First 2 × 2 sub-matrix:
[[1 2]
 [5 6]]


In [14]:
# Question 13
print("Last 2 × 2 sub-matrix:")
print(matrix[-2:, -2:])

Last 2 × 2 sub-matrix:
[[11 12]
 [15 16]]


In [15]:
# Question 14
array_3d = np.arange(1, 19).reshape(2, 3, 3)

print("3D Array:")
print(array_3d)

print("First matrix:")
print(array_3d[0])

3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
First matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Question 15
print("Second matrix:")
print(array_3d[1])

Second matrix:
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [17]:
# Question 16
print("Specific element:", array_3d[1, 2, 1])

Specific element: 17


In [18]:
# Question 17
arr = np.arange(1, 21)

even_numbers = arr[arr % 2 == 0]

print("Even numbers:", even_numbers)

Even numbers: [ 2  4  6  8 10 12 14 16 18 20]


In [19]:
# Question 18
odd_numbers = arr[arr % 2 != 0]

print("Odd numbers:", odd_numbers)

Odd numbers: [ 1  3  5  7  9 11 13 15 17 19]


In [20]:
# Question 19
greater_than_10 = arr[arr > 10]

print("Numbers greater than 10:", greater_than_10)

Numbers greater than 10: [11 12 13 14 15 16 17 18 19 20]


In [21]:
# Question 20
less_than_15 = arr[arr < 15]

print("Numbers less than 15:", less_than_15)

Numbers less than 15: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [22]:
# Question 21
indices = np.array([0, 2, 4, 6])

print("Elements at index positions 0, 2, 4, 6:")
print(arr[indices])

Elements at index positions 0, 2, 4, 6:
[1 3 5 7]


In [23]:
# Question 22
indices = np.array([0, -1])

print("First and last elements:")
print(arr[indices])

First and last elements:
[ 1 20]


In [24]:
# Question 23
matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(matrix)

print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("First column:", matrix[:, 0])
print("Last column:", matrix[:, -1])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last row: [21 22 23 24 25]
First column: [ 1  6 11 16 21]
Last column: [ 5 10 15 20 25]


In [25]:
# Question 24
matrix = np.arange(1, 21).reshape(4, 5)

print("Matrix:")
print(matrix)

print("First 3 columns:")
print(matrix[:, :3])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
First 3 columns:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [26]:
# Question 25

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(matrix)

print("\nFirst row:")
print(matrix[0])

print("\nLast row:")
print(matrix[-1])

print("\nFirst column:")
print(matrix[:, 0])

print("\nLast column:")
print(matrix[:, -1])

print("\nMiddle row:")
print(matrix[2])

print("\nMiddle column:")
print(matrix[:, 2])

print("\nTop-left 2 × 2 matrix:")
print(matrix[:2, :2])

print("\nBottom-right 2 × 2 matrix:")
print(matrix[-2:, -2:])

print("\nAll even numbers:")
print(matrix[matrix % 2 == 0])

print("\nAll odd numbers:")
print(matrix[matrix % 2 != 0])

print("\nNumbers greater than 15:")
print(matrix[matrix > 15])

print("\nNumbers less than 10:")
print(matrix[matrix < 10])

print("\nFancy Indexing - 1, 7, 13, 19, 25:")
indices = np.array([0, 6, 12, 18, 24])
print(matrix.flatten()[indices])

print("\nNegative Indexing - 25, 24, 23:")
print(matrix.flatten()[-1])
print(matrix.flatten()[-2])
print(matrix.flatten()[-3])

print("\nLast three rows:")
print(matrix[-3:])

print("\nFirst three columns:")
print(matrix[:, :3])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First row:
[1 2 3 4 5]

Last row:
[21 22 23 24 25]

First column:
[ 1  6 11 16 21]

Last column:
[ 5 10 15 20 25]

Middle row:
[11 12 13 14 15]

Middle column:
[ 3  8 13 18 23]

Top-left 2 × 2 matrix:
[[1 2]
 [6 7]]

Bottom-right 2 × 2 matrix:
[[19 20]
 [24 25]]

All even numbers:
[ 2  4  6  8 10 12 14 16 18 20 22 24]

All odd numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]

Numbers greater than 15:
[16 17 18 19 20 21 22 23 24 25]

Numbers less than 10:
[1 2 3 4 5 6 7 8 9]

Fancy Indexing - 1, 7, 13, 19, 25:
[ 1  7 13 19 25]

Negative Indexing - 25, 24, 23:
25
24
23

Last three rows:
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First three columns:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]
