14/07/2026

Assignment : 21

NumPy assignment : 4

In [2]:
# Question 1
import numpy as np

arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)

print("Original Array:", arr)
print("3 × 4 Matrix:")
print(matrix)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
3 × 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# Question 2
arr = np.arange(1, 17)

matrix = arr.reshape(4, 4)

print("4 × 4 Matrix:")
print(matrix)

4 × 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
# Question 3
arr = np.arange(1, 25)

array_3d = arr.reshape(2, 3, 4)

print("2 × 3 × 4 Array:")
print(array_3d)

2 × 3 × 4 Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [5]:
# Question 4
arr = np.arange(1, 19)

matrix = arr.reshape(3, 6)

print("3 × 6 Matrix:")
print(matrix)

3 × 6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [6]:
# Question 5
arr = np.arange(1, 21)

matrix = arr.reshape(4, -1)

print("Reshaped Matrix:")
print(matrix)

Reshaped Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
# Question 6
matrix = np.arange(1, 13).reshape(3, 4)

new_matrix = matrix.reshape(2, 6)

print("Original 3 × 4 Matrix:")
print(matrix)

print("Reshaped 2 × 6 Matrix:")
print(new_matrix)

Original 3 × 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped 2 × 6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
# Question 7
array_3d = np.arange(1, 13).reshape(2, 3, 2)

array_1d = array_3d.reshape(-1)

print("Original 3D Array:")
print(array_3d)

print("1D Array:")
print(array_1d)

Original 3D Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
# Question 8
matrix = np.arange(1, 10).reshape(3, 3)

array_1d = matrix.flatten()

print("Original Matrix:")
print(matrix)

print("Flattened Array:")
print(array_1d)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [10]:
# Question 9
matrix = np.arange(1, 9).reshape(4, 2)

array_1d = matrix.ravel()

print("Original Matrix:")
print(matrix)

print("Raveled Array:")
print(array_1d)

Original Matrix:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Raveled Array:
[1 2 3 4 5 6 7 8]


In [11]:
# Question 10
matrix = np.arange(1, 9).reshape(2, 4)

print("Original Matrix:")
print(matrix)

print("Using transpose():")
print(matrix.transpose())

print("Using .T:")
print(matrix.T)

Original Matrix:
[[1 2 3 4]
 [5 6 7 8]]
Using transpose():
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Using .T:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [12]:
# Question 11
matrix = np.arange(1, 10).reshape(3, 3)

new_matrix = np.resize(matrix, (2, 6))

print("Original Matrix:")
print(matrix)

print("Resized 2 × 6 Matrix:")
print(new_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Resized 2 × 6 Matrix:
[[1 2 3 4 5 6]
 [7 8 9 1 2 3]]


In [13]:
# Question 12
arr = np.array([10, 20, 30])

matrix = np.resize(arr, (3, 3))

print("Original Array:")
print(arr)

print("Resized 3 × 3 Matrix:")
print(matrix)

Original Array:
[10 20 30]
Resized 3 × 3 Matrix:
[[10 20 30]
 [10 20 30]
 [10 20 30]]


In [14]:
# Question 13
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flattened = matrix.flatten()

flattened[0] = 100

print("Original Array:")
print(matrix)

print("Flattened Array:")
print(flattened)

Original Array:
[[1 2 3]
 [4 5 6]]
Flattened Array:
[100   2   3   4   5   6]


In [15]:
# Question 14
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

raveled = matrix.ravel()

raveled[0] = 100

print("Original Array:")
print(matrix)

print("Raveled Array:")
print(raveled)

Original Array:
[[100   2   3]
 [  4   5   6]]
Raveled Array:
[100   2   3   4   5   6]


In [16]:
# Question 15
array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])

result = np.concatenate((array1, array2))

print("Merged Array:")
print(result)

Merged Array:
[10 20 30 40 50 60]


In [17]:
# Question 16
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

result = np.hstack((matrix1, matrix2))

print("Column-wise Merge:")
print(result)

Column-wise Merge:
[[1 2 5 6]
 [3 4 7 8]]


In [18]:
# Question 17
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

result = np.vstack((matrix1, matrix2))

print("Row-wise Merge:")
print(result)

Row-wise Merge:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
# Question 18
arr = np.arange(1, 13)

parts = np.split(arr, 4)

print("Original Array:")
print(arr)

print("4 Equal Parts:")
print(parts)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
4 Equal Parts:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [20]:
# Question 19
matrix = np.arange(1, 9).reshape(4, 2)

parts = np.split(matrix, 2)

print("Original Matrix:")
print(matrix)

print("2 Equal Parts:")
print(parts)

Original Matrix:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2 Equal Parts:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [21]:
# Question 20
array1 = np.array([1, 2])
array2 = np.array([3, 4])
array3 = np.array([5, 6])

result = np.concatenate((array1, array2, array3))

print("Merged Array:")
print(result)

Merged Array:
[1 2 3 4 5 6]


In [22]:
# Question 21
salary = np.array([25000, 30000, 35000, 40000, 45000])

updated_salary = salary + 5000

print("Original Salary:")
print(salary)

print("Salary After ₹5000 Bonus:")
print(updated_salary)

Original Salary:
[25000 30000 35000 40000 45000]
Salary After ₹5000 Bonus:
[30000 35000 40000 45000 50000]


In [23]:
# Question 22
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])

grace_marks = np.array([5, 5, 10])

updated_marks = marks + grace_marks

print("Original Marks:")
print(marks)

print("Updated Marks:")
print(updated_marks)

Original Marks:
[[70 80 90]
 [60 75 85]]
Updated Marks:
[[ 75  85 100]
 [ 65  80  95]]


In [24]:
# Question 23
arr = np.array([10, 20, 30, 40])

copied_arr = arr.copy()

copied_arr[0] = 100

print("Original Array:")
print(arr)

print("Copied Array:")
print(copied_arr)

Original Array:
[10 20 30 40]
Copied Array:
[100  20  30  40]


In [25]:
# Question 24
arr = np.array([100, 200, 300, 400])

view_arr = arr.view()

view_arr[0] = 999

print("Original Array:")
print(arr)

print("View Array:")
print(view_arr)

Original Array:
[999 200 300 400]
View Array:
[999 200 300 400]


In [26]:
# Question 25

salary = np.array([
    [25000, 30000, 35000],
    [40000, 45000, 50000]
])

# 1. Original Matrix
print("1. Original Salary Matrix:")
print(salary)

# 2. Reshape into 3 × 2
reshaped = salary.reshape(3, 2)

print("\n2. Reshaped 3 × 2 Matrix:")
print(reshaped)

# 3. Flatten the reshaped matrix
flattened = reshaped.flatten()

print("\n3. Flattened Array:")
print(flattened)

# 4. Transpose of original matrix
transposed = salary.T

print("\n4. Transpose:")
print(transposed)

# 5. Increase every salary by ₹2000
updated_salary = salary + 2000

print("\n5. Salary After ₹2000 Increase:")
print(updated_salary)

# 6. Create a copy and modify one value
salary_copy = salary.copy()
salary_copy[0, 0] = 99999

print("\n6. Original Matrix After Copy Modification:")
print(salary)

print("Copy After Modification:")
print(salary_copy)

# 7. Create a view and modify one value
salary_view = salary.view()
salary_view[0, 1] = 88888

print("\n7. Original Matrix After View Modification:")
print(salary)

print("View After Modification:")
print(salary_view)

# 8. Compare outputs
print("\n8. Comparison:")
print("Copy is independent from original.")
print("View shares data with original.")

1. Original Salary Matrix:
[[25000 30000 35000]
 [40000 45000 50000]]

2. Reshaped 3 × 2 Matrix:
[[25000 30000]
 [35000 40000]
 [45000 50000]]

3. Flattened Array:
[25000 30000 35000 40000 45000 50000]

4. Transpose:
[[25000 40000]
 [30000 45000]
 [35000 50000]]

5. Salary After ₹2000 Increase:
[[27000 32000 37000]
 [42000 47000 52000]]

6. Original Matrix After Copy Modification:
[[25000 30000 35000]
 [40000 45000 50000]]
Copy After Modification:
[[99999 30000 35000]
 [40000 45000 50000]]

7. Original Matrix After View Modification:
[[25000 88888 35000]
 [40000 45000 50000]]
View After Modification:
[[25000 88888 35000]
 [40000 45000 50000]]

8. Comparison:
Copy is independent from original.
View shares data with original.
