07/07/2026

Assignment : 18

NumPy assignment : 1

In [7]:
# Question 1
import numpy as np

print("NumPy imported successfully")

NumPy imported successfully


In [8]:
# Question 2
arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# Question 3
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Question 4
arr3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# Question 5
print(arr2d.ndim)

2


In [12]:
# Question 6
print(arr3d.shape)

(2, 2, 3)


In [13]:
# Question 7
print(arr3d.size)

12


In [14]:
# Question 8
print(arr.dtype)

int32


In [15]:
# Question 9
zeros_array = np.zeros((5, 5), dtype=int)

print(zeros_array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
# Question 10
ones_array = np.ones((4, 4), dtype=int)

print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
# Question 11
hundred_array = np.full((3, 3), 100)

print(hundred_array)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [18]:
# Question 12
identity_5 = np.eye(5, dtype=int)

print(identity_5)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [19]:
# Question 13
arr = np.arange(10, 51)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [20]:
# Question 14
arr = np.arange(0, 51, 5)

print(arr)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [21]:
# Question 15
arr = np.linspace(1, 100, 10)

print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [22]:
# Question 16
decimal_array = np.linspace(0.5, 5.0, 10)

print(decimal_array)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [23]:
# Question 17
marks = np.array([78, 85, 92, 67, 74, 88, 95, 81, 69, 90])

print(marks)

[78 85 92 67 74 88 95 81 69 90]


In [24]:
# Question 18
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Dimensions:", marks.ndim)
print("Data Type:", marks.dtype)

Shape: (10,)
Size: 10
Dimensions: 1
Data Type: int32


In [25]:
# Question 19
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
# Question 20
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# Question 21
float_array = np.array([1.5, 2.5, 3.5, 4.5, 5.5])

print(float_array)

[1.5 2.5 3.5 4.5 5.5]


In [28]:
# Question 22
string_array = np.array(["Python", "NumPy", "Pandas", "AI"])

print(string_array)

['Python' 'NumPy' 'Pandas' 'AI']


In [29]:
# Question 23
boolean_array = np.array([True, False, True, True, False])

print(boolean_array)

[ True False  True  True False]


In [30]:
# Question 24
zeros_6 = np.zeros((6, 6), dtype=int)

print(zeros_6)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [31]:
# Question 25
identity_10 = np.eye(10, dtype=int)

print(identity_10)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
